moved active checking to script

diff --git a/vllm_app/template/script.sh.erb b/vllm_app/template/script.sh.erb
--- a/vllm_app/template/script.sh.erb
+++ b/vllm_app/template/script.sh.erb
@@ -45,16 +45,46 @@ export OMP_NUM_THREADS=4
 export NVIDIA_DISABLE_REQUIRE=1
 
 vllm serve $MODEL  --host=localhost --port=$nimport $QUANT_STRING $MULTIPLE_GPUS $TEMPLATE_STR --gpu_memory_utilization 0.8 >& llm.log &
-#source_helpers
-#set -x
-# Wait for the RFDiffusion NIM server to start
-#echo "Waiting for RFDiffusion NIM server to open port 8082..."
-#if wait_until_port_used "localhost:8082" 600; then
-#  echo "Discovered RFDiffusion NIM server listening on port 8082!"
-#else
-#  echo "Timed out waiting for RFDiffusion NIM  server to open port 8082!"
-#  clean_up 1
-#fi
+
+# Unfortunately VLLM responds as port ready long before it is really ready.
+# So wait_until_port_used is modified to check log for actual readiness
+unset -f wait_until_port_used
+
+wait_until_port_used () {
+    local port="${1}"
+    local time="${2:-30}"
+    for ((i=1; i<=time*2; i++)); do
+      port_used "${port}"
+      port_status=$?
+      # echo $port $port_status
+      if [ -f llm.log ]; then
+         if grep "Application startup complete" llm.log; then
+		 return 0
+         else echo "Log exists, Waiting on server start"
+	 fi
+      fi
+      if [ "$port_status" == "127" ]; then
+         echo "commands to find port were either not found or inaccessible."
+         echo "command options are lsof, nc, bash's /dev/tcp, or python (or python3) with socket lib."
+         return 127
+      fi
+      sleep 1
+    done
+    return 1
+  }
+
+# Wait for the NIM server to start
+echo VLLM port is $nimport
+echo "Waiting for VLLM server to open port $nimport..."
+if wait_until_port_used "${host}:${nimport}" 600; then
+  echo "Discovered VLLM server listening on port $nimport!"
+else
+  echo "Timed out waiting for VLLM  server to open port $nimport!"
+  clean_up 1
+fi
+
+sleep 2
+
 
 # Set working directory to home directory
 cd "${HOME}"
