adding a subdir for pipeline chosen in work dir

diff --git a/nf-core/template/script.sh.erb b/nf-core/template/script.sh.erb
--- a/nf-core/template/script.sh.erb
+++ b/nf-core/template/script.sh.erb
@@ -31,11 +31,11 @@ fi
 
 # Copy necessary files and change to the working directory
 if [[ ! -d "$workdir" ]]; then
-    cp "$nfparams" "$workdir/$USER/SLURM_JOB_ID" || { echo "Error: Failed to copy JSON nf-params"; exit 1; }
-    cd "$workdir/$USER/$SLURM_JOB_ID" || { echo "Error: Failed to change to directory $workdir"; exit 1; }
+    cp "$nfparams" "$workdir/$USER/$pipeline_nf/$SLURM_JOB_ID" || { echo "Error: Failed to copy JSON nf-params"; exit 1; }
+    cd "$workdir/$USER/$pipeline_nf/$SLURM_JOB_ID" || { echo "Error: Failed to change to directory $workdir"; exit 1; }
 else
-    cp "$nfparams" "/scratch/general/vast/$USER/$SLURM_JOB_ID" || { echo "Error: Failed to copy JSON nf-params"; exit 1; }
-    cd "/scratch/general/vast/$USER/$SLURM_JOB_ID" || { echo "Error: Failed to change to directory workdir"; exit 1; }
+    cp "$nfparams" "/scratch/general/vast/$USER/$pipeline_nf/$SLURM_JOB_ID" || { echo "Error: Failed to copy JSON nf-params"; exit 1; }
+    cd "/scratch/general/vast/$USER/$pipeline_nf/$SLURM_JOB_ID" || { echo "Error: Failed to change to directory workdir"; exit 1; }
 fi
 
 # Determine if the job should resume
